name: diff_vis
channels:
 # - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - pytest
  - jupyter
  - ipykernel
  - streamlit_tags
  - streamlit==1.9.2