name: diff_vis
dependencies:
- python >= 3.7
- pip >= 20.0.2
- streamlit >= 1.9.2
- pip:
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - pytest
  - jupyter
  - ipykernel
  - watchdog==3.0.0
