name: RTD Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Trigger RTD Build
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.RTDS_WEBHOOK_TOKEN }}" \
          https://readthedocs.org/api/v3/projects/diff_viz/builds/
