name: RTD Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Trigger RTD Build
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.RTDS_WEBHOOK_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"versions": ["latest"], "trigger": "github"}' \
          https://readthedocs.org/api/v3/projects/diff_viz/versions/latest/builds/
